#!/bin/bash

## Util to get xresources
function getxcolor {
	xrdb -query | grep -E "\*\.$1:" | sed -r "s/^[^:]+:\s+//" | tail -n 1
}

## Update BSPWM colors
bspc config normal_border_color $(getxcolor background)
bspc config active_border_color $(getxcolor color8)
bspc config focused_border_color $(getxcolor color9)
bspc config presel_feedback_color $(getxcolor color6)

# For shitty reason, dunst is killed and not launched
dunst &

# Updating betterlockscreen
betterlockscreen -u .config/wpg/.current > /dev/null &

