set viminfo+=n~/.vim/viminfo

" VIM configs
set number

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif


call plug#begin('~/.vim/plugged')

" For sudo edit and others
Plug 'tpope/vim-eunuch'

" For powerline bar
Plug 'itchyny/lightline.vim'

" Linting
Plug 'dense-analysis/ale'

" show +/- in line numbers of a file under git
Plug 'airblade/vim-gitgutter'

" Copy to system clipboard (Requires xsel)
Plug 'christoomey/vim-system-copy'

" Initialize plugin system
call plug#end()

" Required for lightline.vim
set noshowmode
set laststatus=2

