#! /bin/bash

# Processes that should run only single instance
SINGLE_INSTANCES=(vimb sxhkd polybar flameshot dunst picom udiskie greenclip ibus-daemon)
# Kill everything that ran before
for name in ${SINGLE_INSTANCES[@]}; do
	killall -q $name
done
# Making sure this script is run once only
for name in ${SINGLE_INSTANCES[@]}; do
	while pgrep -u $UID -x $name > /dev/null; do sleep 1; done
done

# Setting mouse icon type in the background (root window)
# Maintains the root window (the background) and its behaviour.
xsetroot -cursor_name left_ptr &
xset r rate 280 25

# Screen shot purpose
flameshot &

## systemd automount removable drives
udiskie &

## clipboard manager for rofi
greenclip daemon &

# Input method
ibus-daemon -d

## formerly compton compositor
picom -b &

## Autostart manager
## Check `dex -ad` to see what starts here
dex -a

# Polybar
$HOME/.config/polybar/autostart &

# Notification daemon
dunst &

wpg -m

## Welcom message
sleep 1 && dunstify -a "insane-PC" -u low "Welcome" "1nsane \$hadow & GULU" &

# Updating betterlockscreen
betterlockscreen -u .config/wpg/.current &

# Keyboard binder
sxhkd &
