#! /bin/bash

# Processes that should run only single instance
xdo close -N "Google-chrome" -n "facebook.com"
SINGLE_INSTANCES=(xfce4-panel conky vimb sxhkd polybar flameshot dunst picom udiskie greenclip ibus-daemon xfce-polkit)
# Kill everything that ran before
for name in ${SINGLE_INSTANCES[@]}; do
	killall -q $name
done
# Making sure this script is run once only
for name in ${SINGLE_INSTANCES[@]}; do
	while pgrep -u $UID -x $name > /dev/null; do sleep 1; done
done

xfsettingsd &
xrandr --auto

## Autostart manager
## Check `dex -ad` to see what starts here
dex -a --environment bspwm

/usr/bin/gnome-keyring-daemon --start --components=pkcs11 &
/usr/bin/gnome-keyring-daemon --start --components=secrets &
/usr/bin/gnome-keyring-daemon --start --components=ssh &
sh -c GDK_BACKEND=x11 pamac-tray &

# Setting mouse icon type in the background (root window)
# Maintains the root window (the background) and its behaviour.
xsetroot -cursor_name left_ptr &
xset r rate 280 25

## systemd automount removable drives
udiskie &

## clipboard manager for rofi
greenclip daemon &

# Input method
ibus-daemon -d

## formerly compton compositor
# picom --config $HOME/.config/picom/picom.conf -b &
picom --config $HOME/.config/picom/ibhagwan-picom.conf -b &

# Polybar
$HOME/.config/polybar/autostart &

# Notification daemon
dunst &

# Random wallpaper colors with wpgtk
wpg -m

## Welcom message
sleep 1 && dunstify -a "insane-PC" -u low "Welcome" "1nsane \$hadow & GULU" &

# Updating betterlockscreen
betterlockscreen -u .config/wpg/.current &

# Conky
conky -c $HOME/.config/conky/clock -d &

# DOCK
xfce4-panel --disable-wm-check &

# Keyboard binder
sxhkd &
