#! /bin/sh

# Cleanup BSPWM rules
bspc rule -r "*"
# bspc rule -a "*" state=floating

# Some variables
WINDOW_GAP=10
TOP_GAP=5
BOTTOM_GAP=5
LEFT_GAP=5
RIGHT_GAP=5

bspc config window_gap $WINDOW_GAP;
bspc config top_padding $((-$WINDOW_GAP+$TOP_GAP))
bspc config left_padding $((-$WINDOW_GAP+$LEFT_GAP))
bspc config right_padding $((-$WINDOW_GAP+$RIGHT_GAP))
bspc config bottom_padding $((-$WINDOW_GAP+$BOTTOM_GAP))

bspc config borderless_monocle true
bspc config gapless_monocle false

bspc config top_monocle_padding -$TOP_GAP
bspc config left_monocle_padding -$LEFT_GAP
bspc config right_monocle_padding -$RIGHT_GAP
bspc config bottom_monocle_padding -$BOTTOM_GAP

eval $($HOME/.local/bin/get-mons.sh)

bspc monitor $MONITOR_1 -d I II III IV V VI VII VIII IX X 
if [ ! -z $MONITOR_2 ]; then
	bspc monitor $MONITOR_2 -d I II III IV V VI VII VIII IX X 
fi
#bspc monitor -d ws1 ws2 ws3 ws4 ws5 ws6 ws7 ws8 ws9 ws0
#bspc monitor -d i ii iii iv v vi vii viii ix x
#bspc monitor -d One Two Three Four Five Six Seven Eight Nine Ten
#bspc monitor -d • • • • • • • • • •

# Creates window on right child in tree (default)
bspc config initial_polarity second_child
# When there is only one tiled window, make it monocle
bspc config single_monocle		true
bspc config remove_disabled_monitors	true
bspc config remove_unplugged_monitors	true
## Honor size hints: do not make windows smaller than they wish to be
bspc config honor_size_hints true 
# bspc config merge_overlapping_monitors    true

bspc config border_width         5
bspc config split_ratio          0.52

bspc config pointer_modifier     mod4
bspc config pointer_action1      move
bspc config pointer_action2      resize_side
# this is used to change window mode in sxhkd
#bspc config pointer_action3      resize_corner 

## Fix for Annoying focus stealing of MineTime, Mailspring and other apps (WIP)
# We wait for 1 minute in the startup so all programs will
# start in their corresponding desktop without stealing foucs
# after that we start respecting applications focuses.
bspc config ignore_ewmh_focus true
(sleep 60 && bspc config ignore_ewmh_focus false) &

## Some applications specific predefined rules
# Auto start applications
bspc rule -a TelegramDesktop --one-shot desktop='^9' follow=off
bspc rule -a MineTime --one-shot desktop='^8' follow=off
bspc rule -a Mailspring --one-shot desktop='^8' follow=off
bspc rule -a Google-chrome:facebook.com --one-shot desktop='^9' follow=off

## Regular applications
bspc rule -a Gcolor3 state=floating center=true
bspc rule -a Lxappearance state=floating center=true
bspc rule -a File-roller state=floating center=true
bspc rule -a TelegramDesktop state=pseudo_tiled
bspc rule -a seahorse state=pseudo_tiled
bspc rule -a MineTime state=pseudo_tiled
bspc rule -a Arandr state=floating center=true
bspc rule -a Blueman-manager state=floating center=true
bspc rule -a qt5ct state=floating center=true
bspc rule -a Pavucontrol state=floating center=true
bspc rule -a kanjitomo-reader-Launcher state=floating border=off follow=off
bspc rule -a "Crow Translate" state=floating follow=off
bspc rule -a Ibus-ui-gtk3 state=floating follow=off
bspc rule -a Mozc_renderer state=floating follow=off
bspc rule -a "Manjaro Settings Manager" state=floating center=true
bspc rule -a "VirtualBox Manager" state=floating center=true
bspc rule -a "Nm-connection-editor" state=floating center=true
bspc rule -a "ClipGrab" state=floating center=true
bspc rule -a "Gufw.py" state=floating center=true
bspc rule -a "Gtkhash" state=floating center=true
bspc rule -a "MEGAsync" state=floating
bspc rule -a "Peek" state=floating
bspc rule -a "SimpleScreenRecorder" state=floating center=true
bspc rule -a "Wpg" state=floating center=true
bspc rule -a "Grub-customizer" state=floating center=true

## Others (Not used)
# bspc rule -a '*' follow=on state=pseudo_tiled
# bspc rule -a kitty desktop='^1' follow=on state=pseudo_tiled

# bspc rule -a spotify state=pseudo_tiled
# bspc rule -a transmission-gtk state=pseudo_tiled
# bspc rule -a conky sticky=on manage=off lower=on

## Browsers # Still need to know what really private mode does
# bspc rule -a google-chrome-stable private=on
# bspc rule -a chromium private=on
# bspc rule -a firefox private=on
# bspc rule -a midori private=on

# Solution for java applications problems
# But this creates for problems for docks, planks and window switchers.
# wmname LG3D

# Found a better solution to export this
# Works awsomely
export _JAVA_AWT_WM_NONREPARENTING=1

# bspc config external_rules_command $HOME/.config/bspwm/scripts/external_rules.sh

bspc subscribe node_add | \
	threshold_width=200 \
	threshold_height=200 \
	minimum_tile_width=100 \
	minimum_tile_height=100 \
		$HOME/.config/bspwm/scripts/small-window.sh &

# Autostarts are moved to .config/bspwm/autostart
$HOME/.config/bspwm/autostart &
