#! /bin/sh

# Cleanup BSPWM rules
bspc rule -r "*"

# Autostarts are moved to .config/bspwm/autostart
$HOME/.config/bspwm/autostart &

bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor -d ws1 ws2 ws3 ws4 ws5 ws6 ws7 ws8 ws9 ws0
#bspc monitor -d i ii iii iv v vi vii viii ix x
#bspc monitor -d One Two Three Four Five Six Seven Eight Nine Ten
#bspc monitor -d • • • • • • • • • •

$HOME/.config/bspwm/scripts/reset-gap.sh

# Creates window on left child in tree
bspc config initial_polarity second_child
# When there is only one tiled window, make it monocle
bspc config single_monocle		true
bspc config remove_disabled_monitors	true
bspc config remove_unplugged_monitors	true
## Honor size hints: do not make windows smaller than they wish to be
bspc config honor_size_hints true 
# bspc config merge_overlapping_monitors    true

bspc config border_width         5
bspc config split_ratio          0.52

bspc config pointer_modifier     mod4
bspc config pointer_action1      move
bspc config pointer_action2      resize_side
bspc config pointer_action3      resize_corner

## coloring ####
bspc config normal_border_color		"#111824"
bspc config focused_border_color	"#FF8484"

## Wallpaper for each workspace
#bspc subscribe desktop_focus blabla

## Some applications specific predefined rules
# Auto start applications
bspc rule -a TelegramDesktop --one-shot desktop='^9'
bspc rule -a vimb:facebook --one-shot desktop='^9'
bspc rule -a MineTime --one-shot desktop='^8'
bspc rule -a Mailspring --one-shot desktop='^8'

## Fix for Annoying focus stealing of MineTime (WIP)
# PREV_IGNORE_EWMH_FOCUS=$(bspc config ignore_ewmh_focus)
# bspc config ignore_ewmh_focus true
# bspc rule -a MineTime --one-shot desktop='^8'
# minetime &
# bspc config ignore_ewmh_focus PREV_IGNORE_EWMH_FOCUS
# unset PREV_IGNORE_EWMH_FOCUS


## Regular applications
bspc rule -a Gcolor3 state=floating center=true
bspc rule -a Lxappearance state=floating center=true
bspc rule -a File-roller state=floating center=true
bspc rule -a TelegramDesktop state=pseudo_tiled
bspc rule -a seahorse state=pseudo_tiled
bspc rule -a MineTime state=pseudo_tiled

## Others (Not used)
# bspc rule -a '*' follow=on state=pseudo_tiled
# bspc rule -a kitty desktop='^1' follow=on state=pseudo_tiled

# bspc rule -a spotify state=pseudo_tiled
# bspc rule -a nautilus state=pseudo_tiled
# bspc rule -a skype state=pseudo_tiled
# bspc rule -a transmission-gtk state=pseudo_tiled
# bspc rule -a conky sticky=on manage=off lower=on
# bspc rule -a yad state=floating

## Browsers
# bspc rule -a google-chrome-stable private=on
# bspc rule -a chromium private=on
# bspc rule -a firefox private=on
# bspc rule -a midori private=on
