#!/bin/bash

### Installing script dependencies
# base-devel to build from AUR
sudo pacman -Sy --needed base-devel
# Installing PARU
git clone https://aur.archlinux.org/paru.git
cd paru
makepkg -si
cd ..
rm -rf paru

### Adding Dotfile management functionality
# Backup Directory for existing files (That will be overwritten)
mkdir -p $HOME/rcbackup
[ -d $HOME/.linux-dots ] && mv $HOME/.linux-dots $HOME/rcbackup
mkdir -p $HOME/.linux-dots/.git
/usr/bin/git clone https://github.com/rahatzamancse/linux-dots.git --bare $HOME/.linux-dots/.git
dotfiles="/usr/bin/git --git-dir=$HOME/.linux-dots/.git --work-tree=$HOME"
$dotfiles config --local status.showUntrackedFiles no

# Moving existing important rc files to a safe place
affectedfiles=$($dotfiles ls-files -dm -- ~ | sort -u)
[[ ! -z "$affectedfiles" ]] && cp -v $affectedfiles -t $HOME/rcbackup/
[ -f $HOME/.zshrc ] && mv $HOME/.zshrc $HOME/rcbackup/

# Home configs go brrrr...
$dotfiles checkout -f

# Installing other deps
cat $HOME/.linux-dots/deps.txt | paru -S --needed -

### Removing Bloats
bloats=(
    $(cat $HOME/.linux-dots/bloats.txt)
)

expkgs=($(
    comm -23 \
        <(pacman -Qqt | sort) \
        <(echo base | tr ' ' '\n' | cat <(pacman -Sqg base-devel) - | sort -u)
))

detectedbloatpkgs=($(
    comm -12 \
        <(echo ${expkgs[@]} | tr ' ' '\n' | sort -u) \
        <(echo ${bloats[@]} | tr ' ' '\n' | sort -u)
))

if [ ${#detectedbloatpkgs[@]} -eq 0 ]; then
    echo "Your system is bloat free!!!"
else
    rmpkgs=$(
        zenity --list --checklist \
            --title "Remove bloat packages" \
            --text "Select the bloat packages to remove" \
            --column "" --column "Package" \
            True $(echo ${detectedbloatpkgs[@]} | sed 's/ / True /g')
    )
    rmpkgs=${rmpkgs//|/ }

    if [ ${#rmpkgs[@]} -eq 0 ]; then
        echo "No packages are selected to remove."
    else
        sudo pacman -Rs $rmpkgs
    fi
fi

### Installing My Packages
mypkgs=(
    $(cat $HOME/.linux-dots/mypkgs.txt)
)

if [ ${#mypkgs[@]} -eq 0 ]; then
    echo "You do not have any favourite packages"
else
    installmypkgs=$(
        zenity --list --checklist \
            --title "Install packages" \
            --text "Select the packages to install" \
            --column "" --column "Package" \
            True $(echo ${mypkgs[@]} | sed 's/ / True /g')
    )
    installmypkgs=${installmypkgs//|/ }

    # Install the selected packages, or just upgrade system
    paru -S --needed ${installmypkgs[@]}
fi

### Removing Orphan packages
if [[ $(pacman -Qtdq) ]]; then
    sudo pacman -Rns $(pacman -Qtdq)
else
    echo "Your system has no orphaned packages"
fi

### Adding wallpapers
if zenity --question --text="Do you want to download wallpapers from Google Drive as zip?"; then
    wallzipid=$(zenity --entry --text "Please Enter the wallpaper zip google drive file ID")
    walldir=$(zenity --file-selection --title="Choose a directory for your wallpapers" --directory)
    echo "Downloading wallpapers: ${walldir}"
    gdown "https://drive.google.com/uc?id=$wallzipid" 
else
    echo "Not Downloading wallpapers"
fi


echo "Now please reboot your machine"